### ISSUE TITLE
Flatpak build

### ISSUE THREAD

**Issue by LeandroStanger** [EnergetiCode/gamazing#1]
Please, consider supporting [Flatpak](http://docs.flatpak.org/en/latest/introduction.html#reasons-to-use-flatpak) and publishing gamazing on [Flathub](https://github.com/flathub/flathub/wiki/App-Submission).

**Comment by taikelbia** [comment]
> Please, consider supporting [Flatpak](http://docs.flatpak.org/en/latest/introduction.html#reasons-to-use-flatpak) and publishing gamazing on [Flathub](https://github.com/flathub/flathub/wiki/App-Submission).

This is already a possibility.
gamazing will be released with Flatpak, Snap and AppImage versions! 😃🚀
